import React from 'react';
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ToastProvider } from '@/components/providers/toaster-provider';

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  modal: React.ReactNode; // Dodanie propa modal jako opcjonalnego
}

export default function RootLayout({
  children,
  modal
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="h-full ">
          <div className="fixed  mx-auto z-50">
            <Navbar />
          </div>
          <main className="flex justify-center overflow-hidden ">
            <div className="max-w-[1440px] bg-white w-full">
              <ToastProvider />
              {children}
              {modal && modal} {/* Renderowanie modala, jeśli istnieje */}
            </div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}