import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import Navbar from '@/components/navbar'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
 })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <div className="h-full ">
      <div className="fixed  mx-auto z-50">
        <Navbar />
      </div>
      <main className="flex justify-center  overflow-hidden">
  <div className="max-w-[1440px] bg-white w-full">
    {children}
  </div>
</main>
    </div>
      </body>
    </html>
  )
}
